version: 2.0
jobs:
    build:
        docker:
            - image: mono:latest
        working_directory: ~/rsct/
        steps:
            - checkout

            - run:
                name: Install package dependencies
                command: |
                    apt-get update &&
                    apt-get install -y sox

            - run:
                name: Restore NuGet dependencies
                command: nuget restore

            - run:
                name: Build
                command: msbuild /p:Configuration=Release RuneScapeCacheTools.sln

            - run:
                name: Test
                command: mono --debug packages/xunit.runner.console.*/tools/net461/xunit.console.exe RuneScapeCacheToolsTest/bin/Release/RuneScapeCacheToolsTest.dll

            - run:
                name: Merge assemblies
                command: |
                    nuget install ILRepack -OutputDirectory packages &&
                    mono packages/ILRepack.*/tools/ILRepack.exe /out:artifacts/rsct.exe RuneScapeCacheToolsCLI/bin/Release/rsct.exe RuneScapeCacheToolsCLI/bin/Release/*.dll

            - store_artifacts:
                path: artifacts/
